#!/usr/bin/env python3

# Copyright (C) 2020 Isaac Weintraub
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

import subprocess as sp
import sys as sys
import time as time
import os.path


def capture_command(args):
    result = sp.run(args, stdout=sp.PIPE, stderr=sp.PIPE)
    if result.returncode:
        print("Error running {}: {}".format(args, result.stderr.decode("utf8")), end="")
        sys.exit(result.returncode)
    return result.stdout[:-1].decode("utf8")


def main(pkg_name: str, version_location: str):
    project_name = pkg_name.upper()
    rev_parse = sp.run(["git", "rev-parse", "HEAD"], stdout=sp.PIPE, stderr=sp.PIPE)
    has_commits = not bool(rev_parse.returncode)
    commit_hash = (
        rev_parse.stdout[:-1].decode("utf8")
        if has_commits
        else "0" * 40
    )

    email = capture_command(["git", "config", "user.email"])
    if not email:
        print(
            "error: your Git credentials are not configured. Please configure them, i.e.\n    `git config user.email gburdell3@gatech.edu`\n    `git config user.name 'Burdell, George P'`"
        )
        sys.exit(128)
    if len(email) > 50:
        print("error: email is too long")
        sys.exit(129)

    timestamp = int(time.time())
    dirty_working_tree = bool(sp.run(["git", "diff", "--quiet"]).returncode)

    if has_commits:
        branch = capture_command(["git", "rev-parse", "--abbrev-ref", "HEAD"])
        log = sp.run(
            ["git", "log", '--format=format:"%h"', "origin/{0}..{0}".format(branch)],
            stdout=sp.PIPE, stderr=sp.PIPE
        )
        remote_up_to_date = not bool(log.returncode) and not bool(
            log.stdout[:-1].decode("utf8")
        )
    else:
        remote_up_to_date = False
    version_h = f"""// This file is automatically generated. Do not edit.
#ifndef {project_name}_VERSION_INFO_H
#define {project_name}_VERSION_INFO_H

#include <stdbool.h>

// If anything's been committed previously. If not,
// commit hashes are defined as zero
#define PREVIOUS_COMMITS_EXIST {str(has_commits).lower()}
// Git commit hash that's being built
#define COMMIT_HASH_STRING "{commit_hash}"
#define COMMIT_HASH_U64 0x{commit_hash[:16]}
// If you're building with uncommitted changes
#define DIRTY_WORKING_TREE {str(dirty_working_tree).lower()}
// If you have commits that aren't on remote
// or your branch doesn't have a remote
#define REMOTE_UP_TO_DATE {str(remote_up_to_date).lower()}

#endif // {project_name}_VERSION_INFO_H"""
    update_file = True
    if os.path.exists(version_location):
        with open(version_location, "r") as file:
            file_status = file.read()
            update_file = (file_status != version_h)
    if update_file:
        with open(version_location, "w+") as file:
            file.write(version_h)


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print("usage: {} <package name> <output path>".format(sys.argv[0]))
        sys.exit(1)
    main(sys.argv[1], sys.argv[2])
